### PR TITLE
Add front page admonition announcement to upcoming ohw event in spanish

### PR DESCRIPTION
**Pull request by emiliom**
Admonition content is in Spanish. Links to event announcement I posted in our GitHub Discussions.

At the SC meeting on Jan 18, we agreed that adding this announcement was a good idea.

### CODE REVIEW

**Review by abkfenris — APPROVED** [review]
I think that looks good, but I don't speak Spanish...maybe it's worth adding some context in English too? 'Mind the dust as OHW goes multi lingual, multi season, and around the world'

**Comment by emiliom** [comment]
> I think that looks good, but I don't speak Spanish...maybe it's worth adding some context in English too? 'Mind the dust as OHW goes multi lingual, multi season, and around the world'

I was hesitant to have the exact same text in English, too, to avoid bloat on the front page. But I like the gist of what you're suggesting -- ie, not the exact, translated text, but brief context in English. I'll do that. Thanks!

**Comment by abkfenris** [comment]
Also feel free to throw that above OHW23, since it's sooner.

**Comment by abkfenris** [comment]
Maybe 'Past OHW events' should become 'OHW Events'. On the page we can split things up by present, future, past, but it would also give a spot to add more info to the site while not building out a full page.

**Comment by emiliom** [comment]
@abkfenris what do you think about the changes I made?

> Maybe 'Past OHW events' should become 'OHW Events'. On the page we can split things up by present, future, past, but it would also give a spot to add more info to the site while not building out a full page.

I like that. But I think I'll leave it for a separate PR. Do you want to take a crack? Changing the page title and menu label to "OHW Events" is easy. But if we also change the filename from "pasthackweeks" to, say, "ohwevents", that'll take the extra find-and-replace step to update page/link navigation.

**Comment by abkfenris** [comment]
@emiliom Looks good. Ya we can leave that for another PR.

**Pull request merged**
