### PR TITLE
workaround https://github.com/actions/upload-artifact/issues/38

### PR DESCRIPTION
**Pull request by ocefpaf**
The artifact is defective due to the lack of permissions :-(

This is the suggested workaround until they fix it upstream.

- [x] waiting on https://github.com/David-Byrne/jekyll-diff-action/issues/4 to merge this one.

### CODE REVIEW

**Comment by ocefpaf** [comment]
The diff is working but the comment back functionality is not. See https://github.com/oceanhackweek/oceanhackweek.github.io/pull/51/checks?check_run_id=525775319#step:4:229

**Comment by emiliom** [comment]
> The artifact is defective due to the lack of permissions :-(
>
> This is the suggested workaround until they fix it upstream.

That's not posted as a question to me, so I assume you're referring to permissions outside your and my control? Plus, if you don't have full, unmitigated permissions on the entire https://github.com/oceanhackweek real estate, let me know and I'll fix it.

I'm also assuming you're not looking for my review or merge here :confused:

**Comment by ocefpaf** [comment]
> That's not posted as a question to me, so I assume you're referring to permissions outside your and my control? Plus, if you don't have full, unmitigated permissions on the entire [@oceanhackweek](https://github.com/oceanhackweek) real estate, let me know and I'll fix it.

It is not a question and it is not about the permission here. This GH action creates a zipped artifact without the proper permissions for us to extract it. See the issue in the title.

This PR implements a workaround for that issue until they fix it by creating a tarball of the directory tree before the action zips the artifact. We'll have to extract it twice but the original file and directory permissions will preserved.

> I'm also assuming you're not looking for my review or merge here

Nope. Just trying to fix the diff action now. It works to produce the diff but it fails to comment it back in the PR. We should be seeing this here:

```diff
--- /jekyll-diff-action/old/applicant-info.html
+++ /jekyll-diff-action/new/applicant-info.html
@@ -86 +86 @@
-<p>If you are ready to apply, please use the application form <a href=\"https://form.jotform.com/oceanhack/2019\">https://form.jotform.com/oceanhack/2019</a></p>
+<p>If you are ready to apply, please use the application form <a href=\"https://form.jotform.com/oceanhack/2020\">https://form.jotform.com/oceanhack/2020</a></p>
```

Which is virtually the same as looking into the markdown diff but helpful when there are more HTML changes than just simple text.

**Comment by ocefpaf** [comment]
@emiliom What do you think about https://github.com/ocefpaf/oceanhackweek.github.io/commit/a62cd0e6d211974961593f2b9194eb0e4fa6981e? Useful or should we remove the `jekyll-diff-action`? BTW, before we merge this I need to revert that last commit.

**Comment by emiliom** [comment]
I first need to be sure I understand what the diff GH action will do. Earlier you said this:

> This PR implements a workaround for that issue until they fix it by creating a tarball of the directory tree before the action zips the artifact. We'll have to extract it twice but the original file and directory permissions will preserved.

So, between that and maybe something else you've said, my understanding is that this GH action will generate a tarball after each PR merge, that people can download and decompress to view the web site changes locally as static pages. Typically these PR merges would be on a dev/draft branch, so we're not impacting the live web site.

Am I getting that right? If so, that seems pretty useful. Specially to me! I want to encourage people to submit PR's, but still not make it hard on myself to allow others to view the suggested changes.

**Comment by ocefpaf** [comment]
> So, between that and maybe something else you've said, my understanding is that this GH action will generate a tarball after each PR merge, that people can download and decompress to view the web site changes locally as static pages. 

Yep. We are using two GH actions here. One that builds the site and save the artifact that you can inspect. The other one is the jekyll-diff that will comment back the PR diff on the built HTML.

> Typically these PR merges would be on a dev/draft branch, so we're not impacting the live web site.

This is not implemented here but I don't see the point unless we really want a live webpage for inspection in a draft website. (I was hoping for a GH action that would facilitate that but there is no such thing.)

> Am I getting that right? If so, that seems pretty useful. Specially to me! I want to encourage people to submit PR's, but still not make it hard on myself to allow others to view the suggested changes.

Yep. This helps us review PRs here (jekyll-diff) and locally (built artifact).

**Comment by ocefpaf** [comment]
@emiliom this is ready for a review and merge now.

**Pull request merged**
