### PR TITLE
Generalize statement about project proposal deadline

### PR DESCRIPTION
**Pull request by emiliom**
Also removed admonition stating that the page was still being updated

### CODE REVIEW

**Comment by ocefpaf** [comment]
Sorry, I'm on mobile and I missed you asked for Cathy's review. Just want to get this in ASAP b/c of the deadline but we can amend the text if necessary.

**Comment by cathmmitchell** [comment]
@ocefpaf merged as I was reading it - I'm happy with it

**Comment by ocefpaf** [comment]
> @ocefpaf merged as I was reading it - I'm happy with it

Too fast to mess to let you send you input and too slow to save you from reading it. That is the perfect spot to mess up a review process!

**Comment by emiliom** [comment]
No worries! I flagged Cath mainly b/c she was the last one to comment about this on Slack. Thanks for reviewing and merging.

**Pull request merged**
