### PR TITLE
Integrate resources pages into a single OHW22 menu

### PR DESCRIPTION
**Pull request by emiliom**
I've overhauled @abkfenris's initial exposure (PR #167) of the "resources" pages. Here, all those pages are integrated into a single OHW22 menu column (toctree). The bulk of those pages are now under directory `ohw22/ev` (ev = event; I wanted to keep it very short and not fully intelligible).

I've also exposed the schedule page (still a stub) more prominently.

Some things are still not updated from OHW21 (I wasn't trying to do that), a couple of pages are stubs, and the initial OHW22 page should probably be modified so it presents the "event" pages more prominently and not just via the menu. This is meant for discussion of the structure I'm proposing; this is an alternative to PR #167.

Includes the tweaks I proposed in https://github.com/abkfenris/oceanhackweek.github.io/pull/2

### CODE REVIEW

**Comment by abkfenris** [comment]
The menu structure looks good, but I still think the resources should be their own directory (outside of an events) so that we don't end up duplicating them for every event.

Then we can use the [version switcher](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/configuring.html#add-a-dropdown-to-switch-between-docs-versions) going forwards. 
image


For some reason I never got a notification for your PR against my branch....

**Comment by emiliom** [comment]
> The menu structure looks good, but I still think the resources should be their own directory (outside of an events) so that we don't end up duplicating them for every event.
> 
> Then we can use the [version switcher](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/configuring.html#add-a-dropdown-to-switch-between-docs-versions) going forwards.
image

I think we do end up needing to duplicate and tweak the resources pages (or at least some of them) every year, because some details change or need to be updated. But, we can decide next week whether resources (or whatever we call it) is its own directory or is under the event directory. As long as we present a clear event view to users, the internal folder structure shouldn't make a difference.

> For some reason I never got a notification for your PR against my branch....

How odd

**Comment by emiliom** [comment]
@leewujung can you take a look at this proposed organization and layout and let us know what you think? Thanks.

**Comment by emiliom** [comment]
@abkfenris what path should we take? Let's try to make a decision soon, so we can turn our attention to content.

How about a quick call on Tuesday?

**Comment by emiliom** [comment]
#172 supersedes this PR. I'll close this one.

**Pull request closed without merging**
