### PR TITLE
Conda on the hub and Python learning resources

### PR DESCRIPTION
**Pull request by abkfenris**
Bringing back some of the instructions on how to use Conda on the hub, as well as some of the resources for learning Python and R.

### CODE REVIEW

**Comment by abkfenris** [comment]
Updated pages:
- https://deploy-preview-175--oceanhackweek-preview.netlify.app/resources/prep/learning_python_r.html
- https://deploy-preview-175--oceanhackweek-preview.netlify.app/resources/prep/conda.html

**Comment by ocefpaf** [comment]
@abkfenris I need your advice. I'm almost done with the 3 asciinema videos on how to create and manage a conda environment. Should we add it to this page,

[resources/prep/conda.html](https://deploy-preview-175--oceanhackweek-preview.netlify.app/resources/prep/conda.html)

or should I just paste them into the optional tutorials folder?

**Review by ocefpaf — APPROVED** [review]

**Comment by abkfenris** [comment]
@ocefpaf I think it would depend on how prescriptive and narrowly focused the videos are? Are they 'here is how to create this specific conda environment to do X', or are they more 'here is how to manage conda'?

**Comment by ocefpaf** [comment]
I think more of the former. Let me finish them and I'll send them your way to get your opinion/review.

**Comment by abkfenris** [comment]
Ok, maybe that might go best under tutorials and linked to from the current page.

Maybe a renaming/rearranging is in order at some point, so we have: 
- Logistics
  - Getting Help
  - Preparation (link to various pages/guides)
    - Python/R learning resources
- Tutorials 
- Projects
- Reference (how does the environment, work)
  - Git
  - Github
  - JupyterHub
  - Conda
- Guides (how to accomplish small specific tasks)
  - Git setup
  - Cloning tutorials
  - Git workflows

**Comment by emiliom** [comment]
I like the breakup into separate pages for conda vs Python & R. Plus, yeah, the previous "Conda, Python, R" page seemed old and not the spiffy OHW21 content. Thanks!

**Pull request merged**
