### PR TITLE
Move site to Sphinx

### PR DESCRIPTION
**Pull request by abkfenris**
Moved the site to Sphinx, with ABlog and myst-nb to allow blog style posts and reading of markdown and notebooks (currently not working right). Also rolled in the existing resources site.

I believe we had discussed combining the sites, and adding a blog during our wrap up meeting. I hacked something together based off of the [NCAR-ESDS](https://ncar.github.io/esds/#) and [Chris Holdgraf](https://predictablynoisy.com/)'s blogs. Then something wasn't working (probably the notebooks), I smacked and growled at it a few times, then forgot it about it when the rest of life caught back up after OHW21.

It's definitely a first draft, but I wanted to get it out to see if we want to continue down this route before I put more work in

image

image

image

### CODE REVIEW

**Comment by emiliom** [comment]
Wow, thank you @abkfenris !! This looks really promising. Do you have deployed somewhere public, to give it a closer inspection? I assume that we can have past OHW years as Sphinx versions, which sounds great.

I'd like to bring @lsetiawan into the conversation. @lsetiawan (Don), meet @abkfenris (Alex), and viceversa. Don was involved in OHW18 and OHW19, has been involved in other hackweeks, and has joined the OHW22 organizing team. He had a key role in the web site setup deployed at https://icesat-2.hackweek.io/, which puts a nice front page on top (or the side?) of a JupyterBook site (which starts at https://icesat-2.hackweek.io/intro.html). I think I see pros and cons of each approach. Thoughts?

**Comment by abkfenris** [comment]
What, do you think I'm Vercel and setup to do per commit deploys? (You can pull it down, build the environment, and `make live` or I just pushed the current state to https://alexkerney.com/ohw/index.html )

Hi Don 👋 that IceSat Hackweek page looks slick.

I intentionally didn't try to fully replicate the current snazzy home page while experimenting with this. That's always something we can build back up to. 

[Project Pythia's homepage](https://projectpythia.org/) [git](https://github.com/ProjectPythia/projectpythia.github.io/blob/main/portal/index.md) might be a good example of an option in between custom HTML and basic markdown styling that stays within Sphinx's realm of doc management. It's Markdown with a handful of HTML blocks, and Sphinx directives to style certain blocks. 

I also got creative with the team page, detecting if it was being loaded in [`layout.html`](https://github.com/oceanhackweek/oceanhackweek.github.io/pull/106/files#diff-b1e963aed88ed5899861671ef0d9b39acd0f96826829e593af400949d57426d2), then loading a [team specific page](https://github.com/oceanhackweek/oceanhackweek.github.io/pull/106/files#diff-b1e963aed88ed5899861671ef0d9b39acd0f96826829e593af400949d57426d2) instead that works from our current YAML file of members. I probably could have just done that within [about/team](https://github.com/oceanhackweek/oceanhackweek.github.io/pull/106/files#diff-5ca67ed274dc5767f820bef3d5b549ff4537dca5a6fe21f9cca7a0e40ef83ae4) directly now that I think about it. So, in summary, all sorts of creative trickery is possible.

**Comment by lsetiawan** [comment]
Hey Alex! 😄 Sorry just chimed in. It's been a hectic past few days for me! The demo of the blog style site for OHW looks nice. It does seem to have similarities to [jupyterbook](https://jupyterbook.org/intro.html). Not sure if you have used that, but it's also sphinx based and layout wise, it does take any layout customizations, though I don't see why we would customize since it's pretty coherent with other doc sites with many open-source community out there.

My 2cent on creating the structure like the IceSat Hackweek is that it does give a pretty splash page, but most of the content is actually put into a jupyterbook, which makes it really handy since it takes various formats such as ipynb, markdown, rst, etc. I think a splash page to really draw participants is nice and for the past hackweeks, it seems to work 😄 Anyways, I'm open to other ideas. The template for the icesat2 hackweek can be found [here](https://github.com/uwhackweek/jupyterbook-template).

**Comment by abkfenris** [comment]
I guess it's taken me even longer, as I keep getting distracted by things like family members using inappropriate epoxy.

I'm using a whole bunch of the libraries and themes that were developed for JupyterBook by the Executable Books team, but I wanted to retain some of the flexibility of using Sphinx directly. Since it's a mix of resources, advertising, and blog posts, then it's harder to get things like the ablog configuration to place nicely with JupyterBook. We do get all the format flexibility of JupyterBook by including the MyST-NB parser.

I did figure out the issue with notebooks, my version of JupyterLab wasn't saving the metadata appropriately, so I added some instructions on how to make sure the metadata is correct.

**Comment by emiliom** [comment]
Go right ahead and self merge at your leisure.

**Pull request merged**
