### PR TITLE
Lots of updates for the new website and to prepare for ohw22

### PR DESCRIPTION
**Pull request by emiliom**
First batch of suggested updates. For the OHW22 page, much of the text is place holder or draft.

I've moved around some pages or sections for the OHW content other than OHW22. It's still a work in a progress.

I tried creating an [accessible deployment on my fork](https://emiliom.github.io/oceanhackweek.github.io/ohw22/index.html), for easy viewing by others; but it didn't work -- the styling isn't being applied. Oh well.

### CODE REVIEW

**Comment by abkfenris** [comment]
Right now it doesn't build because sphinx-panels is added as an extension and isn't in the environment. 

I made a PR against your branch that uses sphinx-design and gets the elements from sphinx-panels that you were trying to use working. https://github.com/emiliom/oceanhackweek.github.io/pull/1

**Comment by abkfenris** [comment]
I could also take a look at setting up PR previews, though it might take using a service like Netlify (though I think static site previews are free).

**Review by abkfenris — COMMENTED** [review]
Content wise it looks good to me.

**Comment by emiliom** [comment]
> Right now it doesn't build because sphinx-panels is added as an extension and isn't in the environment.

Right, I forgot to add it to `environment.yml` (I had just installed it into my conda env)! 

> I made a PR against your branch that uses sphinx-design and gets the elements from sphinx-panels that you were trying to use working. https://github.com/emiliom/oceanhackweek.github.io/pull/1

Awesome, thanks. I'll test it locally, but your screenshots look good.

**Comment by abkfenris** [comment]
Ya, I wasn't sure exactly what you were going for style wise (/forgot between getting panels working and updating things to use design), so those aren't committed to that counter PR.

**Comment by emiliom** [comment]
The panel stuff was not part of the updated/visible content in this PR. That's why it was commented out, and their actual content was swiped from elsewhere. It was part of what I experimented with to explore our "palette" of readily available design options.

**Comment by emiliom** [comment]
> I could also take a look at setting up PR previews, though it might take using a service like Netlify (though I think static site previews are free).

That would be very nice, yes. But in the short term (this week), if it's mainly you and I doing significant work on the website (rearranging content, not just wordsmithing), maybe we could make do with pushing the rendered pages to our respective forks at the same time as we submit a PR? That is, if you can tell me the easiest workflow for doing that, since last night I didn't get it right :roll_eyes: 

I do thinking pointing people to rendered pages makes it much, much easier to get input.

**Comment by emiliom** [comment]
Regarding deploying rendered pages in our forks: I found my problem! I just needed to add a `.nojekyll` file. Now it works:
https://emiliom.github.io/oceanhackweek.github.io/index.html

Except, that no longer reflects the current state of this PR, and I don't yet have a clean, smooth workflow for rendering and pushing to my fork's `gh-pages`.

**Comment by abkfenris** [comment]
Ok, I think as soon as you push again to your PR, Netlify will give you a PR preview. It's already gone and added them to all the Dependabot PRs due to packages that have issues 🤦 https://github.com/oceanhackweek/oceanhackweek.github.io/pull/120#issuecomment-1116789475

**Comment by emiliom** [comment]
> Ok, I think as soon as you push again to your PR, Netlify will give you a PR preview

Cool, thanks!!

> It's already gone and added them to all the Dependabot PRs due to packages that have issues :facepalm:

Less cool :roll_eyes:

**Comment by emiliom** [comment]
Should we go ahead and merge this PR? It's not going to update the rendered pages, so we should be good.

**Comment by abkfenris** [comment]
I thought you had more changes in progress?

**Comment by abkfenris** [comment]
It also has the generic JupyterBooks panels on the index, otherwise go ahead.

**Comment by emiliom** [comment]
I do. I'm still working on it. But merging it now will allow us to have a preview on the next PR. Also easier for others to contribute with fewer big changes to deal with.

**Comment by abkfenris** [comment]
Ok, go for it.

**Pull request merged**
