### PR TITLE
More cleanups

### PR DESCRIPTION
**Pull request by ocefpaf**
The theme submodule was its own page too. This removes all the page stuff from it (it was mostly geohackweek related BTW), and moves the assets folder to the root of the page instead of symlinking it (making this a little but friendlier for our Windows users).

I built the page and navigated/tested all the links, it should be OK but I could use another pair of eyes.

### CODE REVIEW

**Comment by ocefpaf** [comment]
The failure here is reported in https://github.com/David-Byrne/jekyll-diff-action/issues/2

**Comment by emiliom** [comment]
> The theme submodule was its own page too. This removes all the page stuff from it (it was mostly geohackweek related BTW), and moves the assets folder to the root of the page instead of symlinking it (making this a little but friendlier for our Windows users).

Awesome, thanks! Yeah, I'd seen all those leftovers from GHW, and the assets folder being a symlink had caught my attention.

> I built the page and navigated/tested all the links, it should be OK but I could use another pair of eyes.

What exactly should I check? Should I clone your branch and build the Jekyll site locally, and test it locally?

> The failure here is reported in David-Byrne/jekyll-diff-action#2

I *think* I'll read that as telling me I don't need to worry about the Jekyll diff failure :confused:

**Comment by ocefpaf** [comment]
> What exactly should I check? Should I clone your branch and build the Jekyll site locally, and test it locally?

Yep. Until I can find a way to deploy the site from a PR into a staging area (and get jekyll-diff to work) we have to inspect it like that.

> I think I'll read that as telling me I don't need to worry about the Jekyll diff failure confused

Yep. It is a problem upstream. GH-actions are a moving target and most of what I'm trying now is already outdated :-(

**Comment by emiliom** [comment]
> GH-actions are a moving target and most of what I'm trying now is already outdated :-(

Well then, I'm glad I haven't tried to play with GH actions yet ...

**Comment by emiliom** [comment]
Alright, I've tested it locally and it looks good.

But more importantly, I'm now set up to test the Jekyll site locally. Thanks for your instructions from yesterday!

**Comment by ocefpaf** [comment]
This one should be OK to be merged. The GH-Actions failures cannot be addressed in this PR. I opened issues upstream to track the problems with them.

**Pull request merged**
