### PR TITLE
update nbgitpuller branch

### PR DESCRIPTION
**Pull request by ocefpaf**
I could not find any other reference to nbgitpuller in our docs. Hopefully these are it.

### CODE REVIEW

**Comment by abkfenris** [comment]
Don't we have written out instructions somewhere on how to get the repo? Since it's not referencing `HEAD` those will probably need a tweak.

**Comment by ocefpaf** [comment]
> Don't we have written out instructions somewhere on how to get the repo? Since it's not referencing `HEAD` those will probably need a tweak.

I think that the only place we have that is in https://github.com/oceanhackweek/oceanhackweek.github.io/pull/179/files#diff-5bba54311529273bae33a39f40e173aade26acf0e1303c714835d2b6534e36cfR80

That is "generic" enough to leave as-is b/c the README they'll get when cloning has the branching information.

If there are other places I'm failing to find them

**Comment by abkfenris** [comment]
> Unrelated to this PR per se, I noticed in that link that the nbgipuller link for RStudio would be different than the link we're using (`&urlpath=rstudio` rather than `&urlpath=lab/tree`). @abkfenris , how should we handle that? I realize we should open a separate issue ...

Currently we can't specify a specific profile for nbgitpuller to try to open. https://github.com/jupyterhub/nbgitpuller/issues/68 Part of that I think is that it will run with whatever profile a user currently has active, so the right way to handle that might be a few appropriately sprinkled __Warnings__.

**Comment by emiliom** [comment]
I'll merge this. It works (I've tested it) and it addresses the original goal of the PR.

**Pull request merged**
